Added UI tests + resport.
hey-bro/Diplom_3 pull request #1
Opened 2022-05-14 08:13 UTC by hey-bro

2022-05-15 18:56 UTC, digranate reviewed
Тоже все очень хорошо и есть небольшие замечания

2022-05-15 18:56 UTC, digranate commented on src/test/java/BuilderTest.java
> +        mainPage.clickButtonSauce();
Не очень хорошо, конечно, что ты все в один тест добавил, но дискутабельно

2022-05-15 18:56 UTC, digranate commented on src/main/java/pages/MainPage.java
> +        return labelBun.hover().is(Condition.visible);
Здесь закралась ошибочка. Смотри - селениде проверяет видимость элемента с помощью анализа атрибута hidden. В данном случае эта видимость реализована по-другому. Покликай кнопку и посмотри, что меняется в классах у элемента при этом. Этот класс и надо использовать при анализе, виден элемент или нет.

2022-05-15 18:56 UTC, digranate commented on src/test/java/LoginUserParameterizedTest.java
> +                {1},
Здесь надуманная параметризация. Она только усложняет понимание, что же покрыто тестами. Лучше было бы все-таки разные тесты с говорящими названиями.

2022-05-15 18:56 UTC, digranate commented on src/test/java/RegistrationNewUserTest.java
> +        mainPage = open(MainPage.MAIN_URL, MainPage.class);
Я в твоих тестах вижу такую штуку - ты пытаешься всегда проверить максимум. Все-таки когда мы пишем не такой end to end тест, тыкающий и проверяющей все сразу, а более точечный, лучше проверять именно то, что заявлено в названии теста. Иначе трудно понять, что конкретно тест проверяет. 
В предыдущем классе у тебя вообще проверки аж в before методе - идея понятна, но смысла особого так делать нет. По крайней мере, в том подходе, что у нас в задании - написать теста на конкретную проверку.
В идеале, структура теста должна быть given дано when действие then проверка

2022-05-21 06:28 UTC, hey-bro commented on src/test/java/BuilderTest.java
> +        mainPage.clickButtonSauce();
Вынес в разные тесты

2022-05-23 06:14 UTC, digranate commented on src/main/java/pages/MainPage.java
> +        return labelBun.hover().is(Condition.visible);
Привет! А это замечание не исправил? Надо поправить!

2022-05-23 16:13 UTC, digranate requested changes
Осталось только переделать анализ видимости. Сделай это, пожалуйста.

2022-05-23 16:13 UTC, digranate commented on src/test/java/BuilderTest.java
> +        mainPage.getLabelFilling().shouldBe(Condition.visible);
Вот здесь надо поправить с помощью анализа класса, как обсуждали!

2022-05-23 17:43 UTC, hey-bro commented on src/test/java/BuilderTest.java
> +        mainPage.getLabelFilling().shouldBe(Condition.visible);
теперь точно должно быть все хорошо

2022-06-06 15:06 UTC, merged